### ISSUE TITLE
worldcat failures

### ISSUE THREAD

**Issue by mvolz** [zotero/translation-server#125]
I have some tests for this isbn: http://www.worldcat.org/search?qt=results_page&q=isbn%3A9791029801297 that used to work but now stopped working with translation-server. But if I open the request translation-server is making in the browser, it works. I wonder if worldcat has blocked translation-server by user agent or similar, maybe? (Or could the translator be broken?)

For our purposes (Wikimedia Foundation) it doesn't matter because we have a subscription to access worldcat via their api, just thought I'd mention it if you were interested in investigating further.

**Comment by dstillman** [comment]
No problem on our end. Both that ISBN and that URL are translating, both on my machine and from https://zbib.org/. Possible they're blocking you based on IP.

**Comment by dstillman** [comment]
(We actually do sometimes see WorldCat failures specifically at institutions with WorldCat subscriptions, where the Cite button on WorldCat that normally gives you RIS just returns an error. We tell people to report it to their library/OCLC as a general WorldCat website problem with no mention of Zotero, since it's not specific to us in any way.)
