### ISSUE TITLE
Empty response from WHO website; consider returning 404 instead? 

### ISSUE THREAD

**Issue by mvolz** [zotero/translation-server#82]
curl -d 'http://apps.who.int/iris/handle/10665/70863' -H 'Content-Type: text/plain' http://127.0.0.1:1969/web

returns
[]

(Also this appears to be a regression of some sort maybe with the translators because it used to work I think - it contains dublin core metadata. )

**Comment by dstillman** [comment]
This isn't specific to translation-server, so closing in favor of the other issue.

**Comment by dstillman** [comment]
(It's a translation-server issue only in that we should never return an empty array for web translation, but really it's a bug in the translator, since it should fall back to webpage saving in the connector too. I suppose we could force a 501 (which is how we communicate inability to translate in translation-server) in cases where such bugs happen, but it's better just to fix them…)
