### ISSUE TITLE
unescapeHTML doesn't work on the translation server

### ISSUE THREAD

**Issue by shadeMe** [zotero/translation-server#88]
We are currently experiencing inconsistent behaviour with the ZU.unescapeHTML function. When called by the Zotero client (v5.0.60), it correctly decodes the string `The Trouble with &ldquo;Evolution of Religion&rdquo;` to `The Trouble with “Evolution of Religion”`. However, when the translator is invoked by the server, the function returns the encoded string without any modifications.

The translator in question can be found [here](https://github.com/ubtue/zotero-translators/blob/eb3c251931ed7f2538f83ffac5b5088fb119f6b0/ubtue_Equinox.js#L64) and the [URL](https://journals.equinoxpub.com/index.php/JCSR/article/view/35722) for reproduction.

**Comment by mrtcode** [comment]
For me the title seems to be correctly decoded. You can check it on https://zbib.org/ (it uses the latest `translation-server`). Although I see unescaped HTML entities in the `Abstract` field, but they are the same in Zotero client too.

I tested with https://journals.equinoxpub.com/JCSR/article/viewArticle/35722 , because the URL you provided contains just a frame and is saved as a web page.

Is `translation-server`up to date?

**Comment by dstillman** [comment]
@shadeMe is using a custom translator that calls `unescapeHTML`. In Node, `unescapeHTML` currently only cleans tags and won't convert most entities:

https://github.com/zotero/zotero/blob/ad27e0c5faed8eaa939ab6e40dfce95c1eefb2ad/chrome/content/zotero/xpcom/utilities.js#L548-L560

There's some ancient code commented out that uses JSDOM (from Simon's original Node translation-server attempt, I assume). I'd be surprised if it worked on current JSDOM, but we can probably get something working with the current version.

**Comment by mrtcode** [comment]
Right, I will try to make it work.
